version: '3.8'
services:
  content-server:
    build: 
      context: ./content-server
    image: gsincl01/analytical-qc-content-server
    container_name: analytical-qc-content-server
    ports:
      - 82:82 

  server:
    build: 
      context: ./server
    image: gsincl01/analytical-qc-server
    container_name: analytical-qc-server
    ports:
      - 9091:9090 

  client:
    build: ./client
    image: gsincl01/analytical-qc-client
    container_name: analytical-qc-client
    ports:
      - 81:80
    depends_on:
      - content-server
      - server
