version: '3.8'
services:
  server:
    build: 
      context: ./server
    image: gsincl01/analytical-qc-server
    container_name: analytical-qc-server
    environment:
      DB_HOST: jdbc:postgresql://ccte-postgres-res.dmap-prod.aws.epa.gov
      DB_PORT: 5432
      DB_NAME: res_gsincl01_qsar
      DB_USER: app_qsar
      DB_PASS: P#BM8&TEEdg@Aj#r
      DB_SCHEMA: sbox_analytical_qc
    expose:
      - "9090"
    networks:
      - server-client 

  client:
    build: ./client
    image: gsincl01/analytical-qc-client
    container_name: analytical-qc-client
    environment:
      SERVER_URL: http://analytical-qc-server:9090
    ports:
      - 81:80
    depends_on:
      - server
    networks: 
      - server-client     
  
networks: 
  server-client:
    driver: bridge
