version: '3.8'
services:
  content-server:
    build: 
      context: ./content-server
    image: gsincl01/analytical-qc-content-server
    container_name: analytical-qc-content-server
    ports:
      - 82:82 

  server:
    build: 
      context: ./server
    image: gsincl01/analytical-qc-server
    container_name: analytical-qc-server
    environment:
      - DB_URL: "${DB_URL}"
      - DB_USER: "${DB_USER}"
      - DB_PASS: "${DB_PASS}"
      - DB_SCHEMA: "${DB_SCHEMA}"
      - DB_DIALECT: "${DB_DIALECT}"
      - DB_DRIVER: "${DB_DRIVER}"
      - CLIENT_URL: "${CLIENT_URL}"
    ports:
      - 9091:9090 

  client:
    build: ./client
    image: gsincl01/analytical-qc-client
    container_name: analytical-qc-client
    ports:
      - 81:80
    environment:
      - VUE_APP_SERVER_URL: "${VUE_APP_SERVER_URL}"
      - VUE_APP_CONTENT_SERVER_URL: "${VUE_APP_CONTENT_SERVER_URL}"
    depends_on:
      - content-server
      - server
