version: '3.8'
services:
  server:
    build: 
      context: ./server
    image: gsincl01/analytical-qc-server
    container_name: analytical-qc-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ccte-postgres-res.dmap-prod.aws.epa.gov:5432/res_gsincl01_qsar
      SPRING_DATASOURCE_USERNAME: app_qsar
      SPRING_DATASOURCE_PASSWORD: P#BM8&TEEdg@Aj#r
      SPRING_DEFAULT_SCHEMA: sbox_analytical_qc
    expose:
      - "9090"
    networks:
      - server-client 

  client:
    build: ./client
    image: gsincl01/analytical-qc-client
    container_name: analytical-qc-client
    environment:
      SERVER_URL: http://analytical-qc-server:9090
    ports:
      - 81:80
    depends_on:
      - server
    networks: 
      - server-client     
  
networks: 
  server-client:
    driver: bridge
